name: Metrics workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build backend
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./reference-app/backend
          file: ./reference-app/backend/Dockerfile
          push: true
          tags: aerosouund/metrics-backend:latest
          
      - name: Build frontend
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./reference-app/frontend
          file: ./reference-app/frontend/Dockerfile
          push: true
          tags: aerosouund/metrics-frontend:latest
